name: wordlestats
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pandas=1.4.2
  - numpy=1.22.3
  - seaborn=0.11.2
  - tweepy=4.8.0
  - beautifulsoup4=4.11.1
  - scipy=1.8.0
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - statsmodels=0.13.2
  - scikit-learn=1.1.1
  - ipython=8.2.0
  - ipdb=0.13.9
  - kaggle=1.5.12