name: wordlestats_slim
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - tweepy
  - beautifulsoup4
  - scipy
  - statsmodels
  - scikit-learn
  - ipython
  - kaggle
  - fastapi
  - uvicorn
  - gunicorn
